services:
  postgres:
    image: postgres:16-alpine
    container_name: migration_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: migration_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: